import prisma from '@/app/lib/db';
import type { Product } from '@prisma/client';
import { notFound } from 'next/navigation';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function updateMetadata(product: Product) {
  metadata.title = product.name;
  metadata.description = product.name;
}

export default async function Page({
  params,
}: {
  params: { company: string; slug: string };
}) {
  let product: Product | null = null;
  try {
    product = await fetchProductData(params.company, params.slug);
  } catch (error) {
    console.log(error);
    if (error instanceof TypeError) notFound();
  }

  if (!product) {
    notFound();
  }

  updateMetadata(product);
  console.log(product);

  return (
    <div>
      <h1>{product.name}</h1>
      <h2>{params.company}</h2>
      <p>{product.ProductScraper.url}</p>
      {/* Hardcoding to ProductScraper[0] for now */}
      <h3>
        {product.ProductScraper[0].ScraperLambda.currencyType}
        {product.ProductScraper[0].ProductScraperHistory[0].price}
      </h3>
      <img
        src={product.ProductScraper[0].ProductScraperHistory[0].imageBase64}
      />
    </div>
  );
}

async function fetchProductData(
  company: string | string[] | undefined,
  slug: string | string[] | undefined
): Promise<Product> {
  if (typeof slug === 'string' && typeof company === 'string') {
    const product = await prisma.product.findFirst({
      include: {
        ProductScraper: {
          include: {
            ProductScraperHistory: {
              orderBy: {
                created: 'desc',
              },
              take: 25,
            },
            ScraperLambda: {
              select: {
                currencyType: true,
              },
            },
          },
        },
      },
      where: { slug: slug, Company: { slug: company } },
    });

    if (!product) throw new TypeError('fetchProductData: product is null');
    return product;
  } else {
    throw new TypeError('fetchProductData: slug or domain is not a string');
  }
}
